spring:
  data:
    mongodb:
      port: 8080
      database: library
  mvc:
    static-path-pattern: static/**

  mongock:
    runner-type: initializingbean
    change-logs-scan-package:
      - ru.otus.library.changelogs

logging:
  level:
    root: info