spring:
  data:
    mongodb:
      port: 0
      database: library

  mongock:
    runner-type: initializingbean
    change-logs-scan-package:
      - ru.otus.library.changelogs

logging:
  level:
    root: error